# -*- coding: utf-8 -*-
"""Model2_run_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pi5qCneCgfwG60TWnoPOujVR-NRnO_7N
"""

import re
import joblib
import lime.lime_text
import numpy as np

# Load the saved model and vectorizer
model = joblib.load('naive_bayes_model2.joblib')
vectorizer = joblib.load('count_vectorizer2.joblib')

# Clean review text function
def clean_review(text):
    return re.sub(r'[^A-Za-z\s]', '', text)

# Function to predict and explain reviews
def predict_review(review):
    # Clean and transform the review
    cleaned_review = clean_review(review)
    review_vectorized = vectorizer.transform([cleaned_review])

    # Make the prediction
    prediction = model.predict(review_vectorized)

    return prediction[0]  # Return only the prediction label

# Function to explain predictions using LIME
def explain_review(review):
    # Predict label
    prediction = predict_review(review)

    # Initialize LIME explainer with correct class names
    explainer = lime.lime_text.LimeTextExplainer(class_names=['OR', 'CG'])  # 0: OR, 1: CG

    # Explain the prediction
    exp = explainer.explain_instance(
        review,  # Original text input for LIME
        lambda x: model.predict_proba(vectorizer.transform(x)),  # Prediction probabilities
        num_features=10  # Number of features to show in the explanation
    )

    # Print the words that influenced the prediction
    print("\nInfluential Words:")
    influential_words = []
    for word, weight in exp.as_list():
        if weight > 0.0:
            influential_words.append((word, weight))

    #print(f"\nPredicted Label: {'CG' if prediction == 1 else 'OR'}")
    return prediction, influential_words

# # Example usage
# if __name__ == "__main__":
#     new_review = "I loved the service and the staff was very friendly!"
#     pred, influential_words = explain_review(new_review)
#     print(influential_words)

